version: "3.7"
services:
  flask:
    container_name: flask
    build: .
    command: gunicorn --bind 0.0.0.0:5000 __init__:app
    expose:
      - 5000
    environment:
      PSQL_HOST: database:5432
      PSQL_DB_NAME: bcoll
      PSQL_USER_NAME: postgres
      PSQL_PASSWORD:
  nginx:
    container_name: nginx
    build: ./nginx-docker/
    ports:
      - "80:80"
  database:
    container_name: database
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: bcoll
