version: "3.7"
services:
  flask:
    container_name: flask
    build: .
    command: gunicorn --bind 0.0.0.0:5000 __init__:app
    expose:
      - 5000
  nginx:
    container_name: nginx
    build: ./nginx-docker/
    ports:
      - "80:80"